"""Closed but expanded skill aliases and related-transferable relationships.

Relationships are conservative: they encode documented adjacency, not
proficiency. React is not Angular. AWS is not Azure.
"""

from __future__ import annotations

# Alias (lowercased, collapsed whitespace) -> canonical label.
ALIAS_TO_CANONICAL: dict[str, str] = {
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "react": "React",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "vue": "Vue",
    "vue.js": "Vue",
    "vuejs": "Vue",
    "angular": "Angular",
    "svelte": "Svelte",
    "html": "HTML",
    "css": "CSS",
    "sass": "Sass",
    "scss": "Sass",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "node.js": "Node.js",
    "node js": "Node.js",
    "node-js": "Node.js",
    "nodejs": "Node.js",
    "express": "Express",
    "express.js": "Express",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "sql": "SQL",
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",
    "sql server": "SQL Server",
    "mssql": "SQL Server",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "kafka": "Kafka",
    "rest": "REST",
    "rest api": "REST",
    "restful": "REST",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "aws": "AWS",
    "amazon web services": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "google cloud": "GCP",
    "linux": "Linux",
    "unix": "Linux",
    "c": "C",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "php": "PHP",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "r": "R",
    ".net": ".NET",
    "dotnet": ".NET",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "keras": "Keras",
    "spark": "Spark",
    "pyspark": "Spark",
    "airflow": "Airflow",
    "dbt": "dbt",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "excel": "Excel",
    "looker": "Looker",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Redshift",
    "huggingface": "Hugging Face",
    "hugging face": "Hugging Face",
    "langchain": "LangChain",
    "openai": "OpenAI",
    "llm": "LLMs",
    "llms": "LLMs",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "nlp": "NLP",
    "pytest": "pytest",
    "jest": "Jest",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium": "Selenium",
    "junit": "JUnit",
    "figma": "Figma",
    "jira": "Jira",
    "salesforce": "Salesforce",
    "sap": "SAP",
}

# Job requirement canonical -> candidate canonicals that count as related (0.5).
# Directional: having TypeScript supports a JavaScript requirement; the reverse
# is not claimed. Cloud providers are not interchangeable.
PARTIAL_CANDIDATE_FOR_JOB: dict[str, frozenset[str]] = {
    "SQL": frozenset({"PostgreSQL", "MySQL", "SQLite", "SQL Server", "Snowflake", "BigQuery"}),
    "JavaScript": frozenset({"TypeScript", "Node.js"}),
    "Spring": frozenset({"Spring Boot"}),
    "Python": frozenset({"FastAPI", "Django", "Flask", "Pandas", "NumPy"}),
    "React": frozenset({"Next.js"}),
    "Node.js": frozenset({"Express", "TypeScript", "JavaScript"}),
    "REST": frozenset({"FastAPI", "Django", "Flask", "Express", "Spring Boot"}),
    "CI/CD": frozenset({"GitHub Actions", "Jenkins", "GitLab"}),
    "Machine Learning": frozenset({"PyTorch", "TensorFlow", "scikit-learn", "Keras"}),
    "HTML": frozenset({"CSS", "React"}),
    "CSS": frozenset({"Sass", "Tailwind CSS"}),
}
