export const queryKeys = {
  me: ["me"] as const,
  health: ["health"] as const,
  profile: (userId?: number | null) => ["profile", userId ?? "anon"] as const,
  jobs: ["jobs"] as const,
  job: (jobId: string) => ["job", jobId] as const,
  jobIntelligence: (jobId: string) => ["job-intelligence", jobId] as const,
  scores: ["scores"] as const,
  score: (jobId: string) => ["score", jobId] as const,
  materials: (jobId: string) => ["materials", jobId] as const,
  interviewPrep: (jobId: string) => ["interview-prep", jobId] as const,
  resumeVersions: ["resume-versions"] as const,
  resumeVersion: (versionId: string) => ["resume-version", versionId] as const,
  jobResumeVersions: (jobId: string) => ["job-resume-versions", jobId] as const,
  applications: ["applications"] as const,
  dashboardSummary: ["dashboard-summary"] as const,
  careerGrowth: ["career-growth"] as const,
};
